name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > packages/db/.env

    - name: Build and Push User App Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: chaitanyashetty47/montm:latest

    - name: Build and Push Webhook Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.webhook
        push: true
        tags: chaitanyashetty47/webhook:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        debug: true
        timeout: 60s
        script: |
          echo "Successfully connected to EC2 instance"
          
          # Stop and remove existing containers
          sudo docker stop montm webhook 2>/dev/null || true
          sudo docker rm montm webhook 2>/dev/null || true
          
          # Remove old images
          sudo docker rmi chaitanyashetty47/montm:latest chaitanyashetty47/webhook:latest 2>/dev/null || true
          
          # Clear Docker cache
          sudo docker system prune -af
          
          # Pull latest images
          sudo docker pull chaitanyashetty47/montm:latest
          sudo docker pull chaitanyashetty47/webhook:latest
          
          # Get public IP
          TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
          
          # Run containers with latest image
          sudo docker run -d --name webhook --pull always -p 3003:3003 chaitanyashetty47/webhook:latest
          
          export BACKEND_URL=$PUBLIC_IP:3003
          sudo docker run -d --name montm --pull always -p 3005:3000 -e BACKEND_URL=$BACKEND_URL -e NEXTAUTH_URL=https://montm.thechaicoder.com chaitanyashetty47/montm:latest
          
          # Verify running containers
          sudo docker ps
          
          echo "Successfully deployed to EC2"

          # Reload Nginx to ensure it picks up any changes
          sudo systemctl reload nginx
          